version: "3"

services:
  app:
    build: .
    command: npm start
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/hashing-password-poc
      PEPPER: 98406f1e8315ebe3cda601619f1e3049
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  postgres:
    image: postgres:13.2-alpine
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hashing-password-poc